[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"

[env]
PORT = "8000"
HLS_PORT = "8000"
RTMP_PORT = "1935"
REDIS_URL = "${{ Redis.REDIS_URL }}"
DB_HOST = "${{ MySQL.MYSQL_HOST }}"
DB_USER = "${{ MySQL.MYSQL_USER }}"
DB_PASS = "${{ MySQL.MYSQL_PASSWORD }}"
FFMPEG_PATH = "/usr/bin/ffmpeg"

[tcp]
ports = [1935, 8000]
